# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext



    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
                    chain:
                        providers: [in_memory, our_db_provider]
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: ROLE_ADMIN
        our_db_provider:
                    entity:
                        class: AppBundle:User
                        property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login

            provider: chain_provider

            access_denied_handler: AppBundle\Security\CustomAccessDeniedHandler

            logout:
                path: /logout
                target: /login

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        # require ROLE_ADMIN for /admin*
       # - { path: ^/, roles: IS_AUTHENTICATED_ANONIMOUSLY, requires_channel: https}
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/create/, roles: ROLE_USER }