<?php

namespace AppBundle\Repository\Movies;

/**
 * producerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class producerRepository extends \Doctrine\ORM\EntityRepository
{
}
