<?php

namespace AppBundle\Repository\Movies;

/**
 * RegisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
